apiVersion: apps/v1
kind: Deployment
metadata:
  name: stat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stat
  template:
    metadata:
      labels:
        app: stat
    spec:
      containers:
      - name: stat
        image: stat
        ports:
          - containerPort: 80